config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/dtgeo.wp5dtc1/dtc51:
      branch: ST510107
      repo: https://gitlab.com/dtgeo.wp5dtc1/dtc51
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/dtgeo.wp5dtc1/dtc51 git:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-persimmon-mule.sh
        container: qc.acc_sloppy-amethyst-wildebeest
  QC.Doc:
    repos:
      gitlab.com/dtgeo.wp5dtc1/dtc51 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-jade-dalmatian.sh
        container: qc.doc_shaky-beige-cuttlefish
      gitlab.com/dtgeo.wp5dtc1/dtc51 git:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-lavender-stingray.sh
        container: qc.doc_baggy-olive-squid
  QC.Lic:
    repos:
      gitlab.com/dtgeo.wp5dtc1/dtc51 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-firebrick-mole.sh
        container: qc.lic_skinny-crimson-tiger
  QC.Sec:
    repos:
      gitlab.com/dtgeo.wp5dtc1/dtc51 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-xanthic-tapir.sh
        container: qc.sec_sickly-sangria-uguisu
  QC.Sty:
    repos:
      gitlab.com/dtgeo.wp5dtc1/dtc51 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-beige-fox.sh
        container: qc.sty_shaggy-sapphire-rat
      gitlab.com/dtgeo.wp5dtc1/dtc51 jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-chocolate-stoat.sh
        container: qc.sty_hazy-pink-argentino
  QC.Uni:
    repos:
      gitlab.com/dtgeo.wp5dtc1/dtc51 pytest:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-pumpkin-frise.sh
        container: qc.uni_flimsy-red-dingo
  QC.Ver:
    repos:
      gitlab.com/dtgeo.wp5dtc1/dtc51 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-grey-wasp.sh
        container: qc.ver_randy-salmon-dachshund
timeout: 5400
