config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/dtgeo.wp5dtc1/dtc51:
      branch: ST510101
      repo: https://gitlab.com/dtgeo.wp5dtc1/dtc51
      subfolder: DTC51/WF5101/ST510101/src
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/dtgeo.wp5dtc1/dtc51 git:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-platinum-dogfish.sh
        container: qc.acc_greasy-mustard-baboon
  QC.Doc:
    repos:
      gitlab.com/dtgeo.wp5dtc1/dtc51 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-cobalt-koala.sh
        container: qc.doc_cloudy-cream-nightingale
      gitlab.com/dtgeo.wp5dtc1/dtc51 git:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-violet-moose.sh
        container: qc.doc_snoopy-thistle-setter
  QC.Lic:
    repos:
      gitlab.com/dtgeo.wp5dtc1/dtc51 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-brown-dane.sh
        container: qc.lic_cozy-violet-buzzard
  QC.Sec:
    repos:
      gitlab.com/dtgeo.wp5dtc1/dtc51 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-indigo-lemur.sh
        container: qc.sec_wimpy-amethyst-shark
  QC.Sty:
    repos:
      gitlab.com/dtgeo.wp5dtc1/dtc51 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-celadon-uakari.sh
        container: qc.sty_lanky-asparagus-bongo
      gitlab.com/dtgeo.wp5dtc1/dtc51 jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.silly-yellow-deer.sh
        container: qc.sty_tasty-ultramarine-guppy
  QC.Uni:
    repos:
      gitlab.com/dtgeo.wp5dtc1/dtc51 commands:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-violet-capybara.sh
        container: qc.uni_cranky-lilac-cuttlefish
  QC.Ver:
    repos:
      gitlab.com/dtgeo.wp5dtc1/dtc51 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.homely-ruby-hippopotamus.sh
        container: qc.ver_gimpy-green-toucan
timeout: 5400
